server:
  port: 8082
  servlet:
    context-path: /quartz
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/think_free?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: comhdoit